[functions]
directory = "functions"

[build]
functions="functions"


[[redirects]]
from = "/auth/login"
to="/.netlify/functions/login"
status=200

[[redirects]]
from = "/auth/callback"
to="/.netlify/functions/callback"
status=200

[[redirects]]
from = "/user/getUserProfile"
to="/.netlify/functions/getUserProfile"
status=200

[[redirects]]
from = "/album/getSavedAlbum"
to="/.netlify/functions/getSavedAlbum"
status=200

[[redirects]]
from = "/traditional/album/getSavedAlbum"
to="/.netlify/functions/getSavedAlbum"
status=200

[[redirects]]
from = "/album/getAlbum"
to="/.netlify/functions/getAlbum"
status=200

[[redirects]]
from = "/traditional/album/getAlbum"
to="/.netlify/functions/getAlbum"
status=200

[[redirects]]
from = "/player/PlayTrack"
to="/.netlify/functions/PlayTrack"
status=200

[[redirects]]
from = "/player/getRecentlyPlayed"
to="/.netlify/functions/getRecentlyPlayed"
status=200

[[redirects]]
from = "/artists/getFollowedArtists"
to="/.netlify/functions/getFollowedArtists"
status=200

[[redirects]]
from = "/traditional/artists/getFollowedArtists"
to="/.netlify/functions/getFollowedArtists"
status=200

[[redirects]]
from = "/artists/getArtistTopTrack"
to="/.netlify/functions/getArtistTopTrack"
status=200

[[redirects]]
from = "/traditional/artists/getArtistTopTrack"
to="/.netlify/functions/getArtistTopTrack"
status=200

[[redirects]]
from = "/artists/getArtistAlbums"
to="/.netlify/functions/getArtistAlbums"
status=200

[[redirects]]
from = "/traditional/artists/getArtistAlbums"
to="/.netlify/functions/getArtistAlbums"
status=200

[[redirects]]
from = "/playlist/getMyPlaylists"
to="/.netlify/functions/getMyPlaylists"
status=200

[[redirects]]
from = "/traditional/playlist/getMyPlaylists"
to="/.netlify/functions/getMyPlaylists"
status=200

[[redirects]]
from = "/playlist/getPlaylistItems"
to="/.netlify/functions/getPlaylistItems"
status=200

[[redirects]]
from = "/traditional/playlist/getPlaylistItems"
to="/.netlify/functions/getPlaylistItems"
status=200


[[redirects]]
from = "/search/search"
to="/.netlify/functions/search"
status=200

[[redirects]]
from = "/traditional/search/search"
to="/.netlify/functions/search"
status=200


[[redirects]]
from = "/*" 
to="/index.html" 
status=200
